services:
  device-management-backend:
    container_name: device-management-backend
    build:
      context: .
      args:
        SERVER_PORT: ${SERVER_PORT}
        TZ: ${TZ}
    ports:
      - '${HOST_PORT:-8080}:${SERVER_PORT:-8080}'
    env_file:
      - .env
    networks:
      - dms-net

networks:
  dms-net: